email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Mark Famous"
tagline: ""
description: "Follow <a href=\"https://micro.blog/mfamous\">@mfamous on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/mfamous\">@mfamous on Micro.blog</a>."
baseurl: ""
url: "http://mark.famousfamily.com"
markdown: "kramdown"
username: "mfamous"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Mark Famous"
name: "Mark Famous"
gravatar_hash: "c1d7e3b7eeb9ffcc948f48c3a08584b8"
avatar: "https://micro.blog/mfamous/avatar.jpg"
full_name: "Mark Famous"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "3644"